### ISSUE TITLE
Is the file name really required?

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/SaveURLtoDropbox#1]
Currently the user has to provide a name to the file he wants to save.
Can this be avoided?

**Comment by diezcami** [comment]
I'm not too familiar with JS so I couldn't submit a pull request, however you could probably check for the value of `name` and set it as something default (eg. `New File.ext`) or as a (sub)string of the URL provided.

**Comment by swapagarwal** [comment]
Okay, so I'll extract the substring after the last *slash* and show it as default.
